#include "ScriptCompiler.h"
#include "ScriptDefine.h"
#include "enum.hpp"


hook_method<bool (CScriptCompiler::*)(char* str, int num)> CScriptCompiler::_StdDefine(SERVER, "CScriptCompiler::StdDefine");
bool CScriptCompiler::StdDefine(char* str, int num) // line 7
{
	return (this->*_StdDefine)(str, num);

	char buf[1024];
	memset(buf, 0, sizeof(buf));
	sprintf(buf, "%s %d", str, num);

	CScriptLine line(buf);
	return m_compiler->OnCommand(line, CCompiler::CMD_DEFINE);
}


hook_method<bool (CScriptCompiler::*)(char* func, char* param, int num, bool isBlockCheck)> CScriptCompiler::_StdDeclare(SERVER, "CScriptCompiler::StdDeclare");
bool CScriptCompiler::StdDeclare(char* func, char* param, int num, bool isBlockCheck) // line 16
{
	return (this->*_StdDeclare)(func, param, num, isBlockCheck);

	char buf[1024];
	memset(buf, 0, sizeof(buf));

	if( isBlockCheck )
		sprintf(buf, "%s %s %d blockcheck", func, param, num);
	else
		sprintf(buf, "%s %s %d", func, param, num);

	CScriptLine line(buf);
	return m_compiler->OnCommand(line, CCompiler::CMD_DECLARE);
}


hook_method<bool (CScriptCompiler::*)(void)> CScriptCompiler::_LoadV2(SERVER, "CScriptCompiler::LoadV2");
bool CScriptCompiler::LoadV2(void) // line 29
{
	return (this->*_LoadV2)();

	return (
		this->CScriptCompiler::StdDefine("ENUM", 0)
	&&  this->CScriptCompiler::StdDeclare("return", ".", FUNC_RETURN, false)
	&&  this->CScriptCompiler::StdDeclare("item", "n", FUNC_ITEM, true)
	&&  this->CScriptCompiler::StdDeclare("event", "n", FUNC_EVENT, true)
	&&  this->CScriptCompiler::StdDeclare("get", "n", FUNC_GET, false)
	&&  this->CScriptCompiler::StdDeclare("inc", "nn", FUNC_INC, false)
	&&  this->CScriptCompiler::StdDeclare("dec", "nn", FUNC_DEC, false)
	&&  this->CScriptCompiler::StdDeclare("EnableSkill", "nn", FUNC_ENABLESKILL, false)
	&&  this->CScriptCompiler::StdDeclare("DisableSkill", "nn", FUNC_DISABLESKILL, false)
	&&  this->CScriptCompiler::StdDeclare("Summon", ".", FUNC_SUMMON, false)
	&&  this->CScriptCompiler::StdDeclare("Skill", "nn", FUNC_SKILL, false)
	&&  this->CScriptCompiler::StdDeclare("CreateItem", ".", FUNC_CREATEITEM, false)
	&&  this->CScriptCompiler::StdDeclare("LostItem", "n", FUNC_LOSTITEM, false)
	&&  this->CScriptCompiler::StdDeclare("HealHP", "n", FUNC_HEALHP, false)
	&&  this->CScriptCompiler::StdDeclare("HealSP", "n", FUNC_HEALSP, false)
	&&  this->CScriptCompiler::StdDeclare("HealAll", ".", FUNC_HEALALL, false)
	&&  this->CScriptCompiler::StdDeclare("Condition", "nnn", FUNC_CONDITION, false)
	&&  this->CScriptCompiler::StdDeclare("Cure", "nn", FUNC_CURE, false)
	&&  this->CScriptCompiler::StdDeclare("AddExtParam", "nnn", FUNC_ADDEXTPARAM, false)
	&&  this->CScriptCompiler::StdDeclare("SubExtParam", "nnn", FUNC_SUBEXTPARAM, false)
	&&  this->CScriptCompiler::StdDeclare("SetMakableWpnItemList", ".", FUNC_SETMAKABLE_WPNLIST, false)
	&&  this->CScriptCompiler::StdDeclare("SetMakableMtlItemList", ".", FUNC_SETMAKABLE_MTLLIST, false)
	&&  this->CScriptCompiler::StdDeclare("RaceAddDamage", "nn", FUNC_RACE_ADD_DAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("RaceSubDamage", "nn", FUNC_RACE_SUB_DAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("AddAttrTolerace", "n?", FUNC_ATTR_ADD_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubAttrTolerace", "n?", FUNC_ATTR_SUB_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddRaceTolerace", "nn", FUNC_RACE_ADD_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubRaceTolerace", "nn", FUNC_RACE_SUB_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamage_Property", "nnn", FUNC_ADDDAMAGE_PROPERTY, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamage_Property", "nnn", FUNC_SUBDAMAGE_PROPERTY, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamage_Size", "nnn", FUNC_ADDDAMAGE_SIZE, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamage_Size", "nnn", FUNC_SUBDAMAGE_SIZE, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamage_Name", "nsn", FUNC_ADDDAMAGE_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamage_Name", "nsn", FUNC_SUBDAMAGE_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamage_SKID", "nnn", FUNC_ADDDAMAGE_SKID, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamage_SKID", "nnn", FUNC_SUBDAMAGE_SKID, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamage_CRI", "nn", FUNC_ADDDAMAGE_CRI, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamage_CRI", "nn", FUNC_SUBDAMAGE_CRI, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_MLEATK", "nnn", FUNC_ADDSTATE_MLEATK, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_MLEATK", "nnn", FUNC_SUBSTATE_MLEATK, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_MLEAttacked", "nnn", FUNC_ADDSTATE_MLEATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_MLEAttacked", "nnn", FUNC_SUBSTATE_MLEATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("AddHealPercent_ITEM", "nsn", FUNC_ADDHEALPERCENT_ITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SubHealPercent_ITEM", "nsn", FUNC_SUBHEALPERCENT_ITEM, false)
	&&  this->CScriptCompiler::StdDeclare("AddHealAmount_Kill", "nn", FUNC_ADDHEALAMOUNT_KILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubHealAmount_Kill", "nn", FUNC_SUBHEALAMOUNT_KILL, false)
	&&  this->CScriptCompiler::StdDeclare("IndestructibleArmor", "n", FUNC_INDESTRUCTIBLE_ARMOR, false)
	&&  this->CScriptCompiler::StdDeclare("IndestructibleWeapon", "n", FUNC_INDESTRUCTIBLE_WEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("AddStateTolerace", "nn", FUNC_ADD_STATE_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubStateTolerace", "nn", FUNC_SUB_STATE_TOLERACE, false)
	&&  this->CScriptCompiler::StdDeclare("BodyAttribute", "n", FUNC_BODY_ATTRIBUTE, false)
	&&  this->CScriptCompiler::StdDeclare("SubRangeAttackDamage", "nn", FUNC_SUB_RANGE_ATTACKDAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("AddRangeAttackDamage", "nn", FUNC_ADD_RANGE_ATTACKDAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("NoDispell", "n", FUNC_NODISPELL, false)
	&&  this->CScriptCompiler::StdDeclare("AddHPdrain", "nn", FUNC_ADD_HPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("SubHPdrain", "nn", FUNC_SUB_HPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("Magicimmune", "n", FUNC_MAGICIMMUNE, false)
	&&  this->CScriptCompiler::StdDeclare("NoJamstone", "n", FUNC_NOJAMSTONE, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPdrain", "nn", FUNC_ADD_SPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPdrain", "nn", FUNC_SUB_SPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("AddMeleeAttackReflect", "n", FUNC_ADD_MELEEATTACK_REFLECT, false)
	&&  this->CScriptCompiler::StdDeclare("SubMeleeAttackReflect", "n", FUNC_SUB_MELEEATTACK_REFLECT, false)
	&&  this->CScriptCompiler::StdDeclare("PerfectDamage", "n", FUNC_PERFECT_DAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("Reincarnation", "n", FUNC_REINCARNATION, false)
	&&  this->CScriptCompiler::StdDeclare("SubSpellCastTime", "n", FUNC_SUB_SPELLCASTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("AddSpellCastTime", "n", FUNC_ADD_SPELLCASTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SplashAttack", "n", FUNC_SPLASH_ATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPconsumption", "n", FUNC_SUB_SPCONSUMPTION, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPconsumption", "n", FUNC_ADD_SPCONSUMPTION, false)
	&&  this->CScriptCompiler::StdDeclare("StartCapture", "s", FUNC_START_CAPTURE, false)
	&&  this->CScriptCompiler::StdDeclare("Incubation", ".", FUNC_INCUBATION, false)
	&&  this->CScriptCompiler::StdDeclare("AddAtk_DamageWeapon", "nn", FUNC_ADDATK_DAMAGEWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("SubAtk_DamageWeapon", "nn", FUNC_SUBATK_DAMAGEWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("AddAtk_DamageArmor", "nn", FUNC_ADDATK_DAMAGEARMOR, false)
	&&  this->CScriptCompiler::StdDeclare("SubAtk_DamageArmor", "nn", FUNC_SUBATK_DAMAGEARMOR, false)
	&&  this->CScriptCompiler::StdDeclare("AddReceiveItem_Race", "nsn", FUNC_ADDRECEIVEITEM_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubReceiveItem_Race", "nsn", FUNC_SUBRECEIVEITEM_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreDEFRace", "n", FUNC_SETIGNOREDEFRACE, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreDEFRace", "n", FUNC_RESETIGNOREDEFRACE, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreDEFClass", "n", FUNC_SETIGNOREDEFCLASS, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreDEFClass", "n", FUNC_RESETIGNOREDEFCLASS, false)
	&&  this->CScriptCompiler::StdDeclare("SetDisappearHPAmount", "snn", FUNC_SET_DISAPPEARHPAMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetDisappearHPAmount", "s", FUNC_RESET_DISAPPEARHPAMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("SetDisappearSPAmount", "snn", FUNC_SET_DISAPPEARSPAMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetDisappearSPAmount", "s", FUNC_RESET_DISAPPEARSPAMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpell", "n", FUNC_SETAUTOSPELL, false)
	&&  this->CScriptCompiler::StdDeclare("AddAtk_ComaRace", "nn", FUNC_ADDATK_COMARACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubAtk_ComaRace", "nn", FUNC_SUBATK_COMARACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddAtk_Coma", "n", FUNC_ADDATK_COMA, false)
	&&  this->CScriptCompiler::StdDeclare("SubAtk_Coma", "n", FUNC_SUBATK_COMA, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPAmount_Action", "nn", FUNC_SUBSPAMOUNT_ACTION, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPAmount_Action", "nn", FUNC_ADDSPAMOUNT_ACTION, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPAmount_Attack", "nn", FUNC_SUBSPAMOUNT_ATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPAmount_Attack", "nn", FUNC_ADDSPAMOUNT_ATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPAmount_AtkRace", "nnn", FUNC_ADDSPAMOUNT_ATKRACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPAmount_AtkRace", "nnn", FUNC_SUBSPAMOUNT_ATKRACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddDestroySP_Attack", "nnn", FUNC_ADDDESTROYSP_ATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("SubDestroySP_Attack", "nnn", FUNC_SUBDESTROYSP_ATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPAmount_KillRace", "nn", FUNC_ADDSPAMOUNT_KILLRACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPAmount_KillRace", "nn", FUNC_SUBSPAMOUNT_KILLRACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddEXPPercent_KillRace", "nn", FUNC_ADDEXPPERCENT_KILLRACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubEXPPercent_KillRace", "nn", FUNC_SUBEXPPERCENT_KILLRACE, false)
	&&  this->CScriptCompiler::StdDeclare("ClassAddDamage", "nnn", FUNC_CLASSADDDAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("ClassSubDamage", "nnn", FUNC_CLASSSUBDAMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("RaceAddDamageSelf", "nn", FUNC_RACEADDDAMAGESELF, false)
	&&  this->CScriptCompiler::StdDeclare("RaceSubDamageSelf", "nn", FUNC_RACESUBDAMAGESELF, false)
	&&  this->CScriptCompiler::StdDeclare("SetInvestigate", ".", FUNC_SETINVESTIGATE, false)
	&&  this->CScriptCompiler::StdDeclare("ResetInvestigate", ".", FUNC_RESETINVESTIGATE, false)
	&&  this->CScriptCompiler::StdDeclare("ModifyDEF_Fraction", "nn", FUNC_MODIFYDEF_FRACTION, false)
	&&  this->CScriptCompiler::StdDeclare("AddGuideAttack", "n", FUNC_ADDGUIDEATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("SubGuideAttack", "n", FUNC_SUBGUIDEATTACK, false)
	&&  this->CScriptCompiler::StdDeclare("AddChangeMonster", "n", FUNC_ADDCHANGEMONSTER, false)
	&&  this->CScriptCompiler::StdDeclare("SubChangeMonster", "n", FUNC_SUBCHANGEMONSTER, false)
	&&  this->CScriptCompiler::StdDeclare("AddCRIPercent_Race", "nn", FUNC_ADDCRIPERCENT_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubCRIPercent_Race", "nn", FUNC_SUBCRIPERCENT_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("SetPushingSkill", "nn", FUNC_SETPUSHINGSKILL, false)
	&&  this->CScriptCompiler::StdDeclare("ResetPushingSkill", "n", FUNC_RESETPUSHINGSKILL, false)
	&&  this->CScriptCompiler::StdDeclare("GetZeny_Range", "nn", FUNC_GETZENY_RANGE, false)
	&&  this->CScriptCompiler::StdDeclare("MulticastEffect", "n", FUNC_MULTICASTEFFECT, false)
	&&  this->CScriptCompiler::StdDeclare("SetExtParamTime", "nnn", FUNC_SETEXTPARAMTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpellTarget", "nnn", FUNC_SETAUTOSPELL_TARGET, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpellSelf", "nnn", FUNC_SETAUTOSPELL_SELF, false)
	&&  this->CScriptCompiler::StdDeclare("SetReceiveZENY_Kill", "nnn", FUNC_SETRECEIVEZENY_KILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddCRI_RANGEATK", "n", FUNC_ADDCRI_RANGEATK, false)
	&&  this->CScriptCompiler::StdDeclare("SubCRI_RANGEATK", "n", FUNC_SUBCRI_RANGEATK, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_RANGEATK", "nn", FUNC_ADDSTATE_RANGEATK, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_RANGEATK", "nn", FUNC_SUBSTATE_RANGEATK, false)
	&&  this->CScriptCompiler::StdDeclare("AddGuildEXP", "nn", FUNC_ADDGUILDEXP, false)
	&&  this->CScriptCompiler::StdDeclare("SetReceiveItem_Group", "n", FUNC_SETRECEIVEITEM_GROUP, false)
	&&  this->CScriptCompiler::StdDeclare("AddReflectMagic", "n", FUNC_ADDREFLECT_MAGIC, false)
	&&  this->CScriptCompiler::StdDeclare("SubReflectMagic", "n", FUNC_SUBREFLECT_MAGIC, false)
	&&  this->CScriptCompiler::StdDeclare("ItemCreate", "sn", FUNC_ITEMCREATE, false)
	&&  this->CScriptCompiler::StdDeclare("IsCompleteCombination", "s", FUNC_ISCOMPLETECOMBINATION, false)
	&&  this->CScriptCompiler::StdDeclare("IsBreakCombination", "s", FUNC_ISBREAKCOMBINATION, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpell_MLEATKED", "nnnn", FUNC_SETAUTOSPELL_MLEATKED, false)
	&&  this->CScriptCompiler::StdDeclare("GetRefineLevel", "n", FUNC_GETREFINELEVEL, false)
	&&  this->CScriptCompiler::StdDeclare("GetSkillLevel", "n", FUNC_GETSKILLLEVEL, false)
	&&  this->CScriptCompiler::StdDeclare("GetPureJob", ".", FUNC_GETPUREJOB, false)
	&&  this->CScriptCompiler::StdDeclare("AddGetItem_Kill", "sn", FUNC_ADDGETITEM_KILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubGetItem_Kill", "sn", FUNC_SUBGETITEM_KILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddParameterValue", "nn", FUNC_ADDPARAMETERVALUE, false)
	&&  this->CScriptCompiler::StdDeclare("EvolutionHomun", ".", FUNC_EVOLUTION_HOMUN, false)
	&&  this->CScriptCompiler::StdDeclare("AddParamTime", "n?", FUNC_ADDPARAMTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SubParamTime", "nnn", FUNC_SUBPARAMTIME, false)
	&&  this->CScriptCompiler::StdDeclare("AddDamageTM_Prop", "nnnn", FUNC_ADDDAMAGETM_PROP, false)
	&&  this->CScriptCompiler::StdDeclare("SubDamageTM_Prop", "nnnn", FUNC_SUBSAMAGETM_PROP, false)
	&&  this->CScriptCompiler::StdDeclare("Cooking", "n", FUNC_COOKING, false)
	&&  this->CScriptCompiler::StdDeclare("SummonNPC", "n", FUNC_SUMMONNPC, false)
	&&  this->CScriptCompiler::StdDeclare("trace", "s", FUNC_TRACE, false)
	&&  this->CScriptCompiler::StdDeclare("v", "n", FUNC_VAR, false)
	&&  this->CScriptCompiler::StdDeclare("lv", "s", FUNC_LOCALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("npcv", "sn", FUNC_NPCVAR, false)
	&&  this->CScriptCompiler::StdDeclare("IncLocalVar", "sn", FUNC_INCLOCALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("DecLocalVar", "sn", FUNC_DECLOCALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("SetLocalVar", "sn", FUNC_SETLOCALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipIsIdentify", "n", FUNC_GETEQUIP_IS_IDENTIFY, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipRefineryCnt", "n", FUNC_GETEQUIP_REFINERYCNT, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipPercentRefinery", "n", FUNC_GETEQUIP_PERCENTREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipRefineryCost", "n", FUNC_GETEQUIP_GETEQUIPREFINERYCOST, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipIsSuccessRefinery", "n", FUNC_GETEQUIP_IS_SUCCESSREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipName", "n", FUNC_GETEQUIP_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipItemIdx", "n", FUNC_GETEQUIP_ITEMIDX, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipWeaponLv", "n", FUNC_GETEQUIP_WEAPONLV, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipIsEnableRef", "n", FUNC_GETEQUIP_IS_ENABLEREF, false)
	&&  this->CScriptCompiler::StdDeclare("LastNpcName", "s", FUNC_LASTNPCNAME, false)
	&&  this->CScriptCompiler::StdDeclare("PcName", ".", FUNC_PCNAME, false)
	&&  this->CScriptCompiler::StdDeclare("OnInit:", ".", FUNC_ONINIT, true)
	&&  this->CScriptCompiler::StdDeclare("OnClick:", ".", FUNC_ONCLICK, true)
	&&  this->CScriptCompiler::StdDeclare("OnTouch:", ".", FUNC_ONTOUCH, true)
	&&  this->CScriptCompiler::StdDeclare("OnMyMobDead:", ".", FUNC_ONMYMOBDEAD, true)
	&&  this->CScriptCompiler::StdDeclare("OnTimer:", "n", FUNC_ONTIMER, true)
	&&  this->CScriptCompiler::StdDeclare("OnCommand:", "s", FUNC_ONCOMMAND, true)
	&&  this->CScriptCompiler::StdDeclare("OnStartArena:", ".", FUNC_ONSTARTARENA, true)
	&&  this->CScriptCompiler::StdDeclare("rand", "nn", FUNC_RAND, false)
	&&  this->CScriptCompiler::StdDeclare("lot", "nn", FUNC_LOT, false)
	&&  this->CScriptCompiler::StdDeclare("GetPCCount", "s", FUNC_GETPCCOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("OnTouchNPC:", ".", FUNC_ONTOUCHNPC, true)
	&&  this->CScriptCompiler::StdDeclare("OnTouch2:", ".", FUNC_ONTOUCH2, true)
	&&  this->CScriptCompiler::StdDeclare("guide", "ssnnnn", FUNC_GUIDE, true)
	&&  this->CScriptCompiler::StdDeclare("npc", "ssnnnnnn", FUNC_NPC, true)
	&&  this->CScriptCompiler::StdDeclare("mob", "nsnnnnn", FUNC_MOB, true)
	&&  this->CScriptCompiler::StdDeclare("warp", "ssnnnn", FUNC_GATE, true)
	&&  this->CScriptCompiler::StdDeclare("trader", "ssnnnn", FUNC_TRADER, true)
	&&  this->CScriptCompiler::StdDeclare("arenaguide", "ssnnnnnn", FUNC_ARENAGUIDE, true)
	&&  this->CScriptCompiler::StdDeclare("hiddenwarp", "ssnnnn", FUNC_HIDDENWARP, true)
	&&  this->CScriptCompiler::StdDeclare("effect", "snnnnnn", FUNC_EFFECT, true)
	&&  this->CScriptCompiler::StdDeclare("dialog", "s", FUNC_DIALOG, false)
	&&  this->CScriptCompiler::StdDeclare("putmob", "snnnnnnnnn", FUNC_PUTMOB, false)
	&&  this->CScriptCompiler::StdDeclare("moveto", "snn", FUNC_MOVETO, false)
	&&  this->CScriptCompiler::StdDeclare("say", "s", FUNC_SAY, false)
	&&  this->CScriptCompiler::StdDeclare("menu", "s?", FUNC_MENU, false)
	&&  this->CScriptCompiler::StdDeclare("getgold", "n", FUNC_GETMONEY, false)
	&&  this->CScriptCompiler::StdDeclare("dropgold", "n", FUNC_DROPMONEY, false)
	&&  this->CScriptCompiler::StdDeclare("getitem", "nn", FUNC_GETITEM, false)
	&&  this->CScriptCompiler::StdDeclare("dropitem", "nn", FUNC_DROPITEM, false)
	&&  this->CScriptCompiler::StdDeclare("setitem", "nn", FUNC_SETITEM, false)
	&&  this->CScriptCompiler::StdDeclare("wait", ".", FUNC_WAITDIALOG, false)
	&&  this->CScriptCompiler::StdDeclare("close", ".", FUNC_CLOSEDIALOG, false)
	&&  this->CScriptCompiler::StdDeclare("hpfullheal", ".", FUNC_HPFULLHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("spfullheal", ".", FUNC_SPFULLHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("hpheal", "n", FUNC_HPHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("spheal", "n", FUNC_SPHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("poisonheal", ".", FUNC_POISONHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("stoneeal", ".", FUNC_STONEHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("curseheal", ".", FUNC_CURSEHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("freezingheal", ".", FUNC_FREEZINGHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("silenceheal", ".", FUNC_SILENCEHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("confusionheal", ".", FUNC_CONFUSIONHEAL, false)
	&&  this->CScriptCompiler::StdDeclare("sellitem", "n", FUNC_SELLITEM, false)
	&&  this->CScriptCompiler::StdDeclare("buyitem", "n", FUNC_BUYITEM, false)
	&&  this->CScriptCompiler::StdDeclare("jobchange", "n", FUNC_JOBCHANGE, false)
	&&  this->CScriptCompiler::StdDeclare("exchange", "nnnn", FUNC_EXCHANGEITEM, false)
	&&  this->CScriptCompiler::StdDeclare("error", ".", FUNC_ERROR, false)
	&&  this->CScriptCompiler::StdDeclare("checkpoint", "snn", FUNC_CHECKPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("store", ".", FUNC_STORE, false)
	&&  this->CScriptCompiler::StdDeclare("cart", "n", FUNC_CART, false)
	&&  this->CScriptCompiler::StdDeclare("dlgwrite", "nn", FUNC_DLGWRITE, false)
	&&  this->CScriptCompiler::StdDeclare("input", ".", FUNC_INPUT, false)
	&&  this->CScriptCompiler::StdDeclare("inputstr", ".", FUNC_INPUTSTR, false)
	&&  this->CScriptCompiler::StdDeclare("compass", "nnnns", FUNC_COMPASS, false)
	&&  this->CScriptCompiler::StdDeclare("nude", ".", FUNC_NUDE, false)
	&&  this->CScriptCompiler::StdDeclare("showimage", "sn", FUNC_SHOW_IMAGE, false)
	&&  this->CScriptCompiler::StdDeclare("changepallete", "nn", FUNC_CHANGE_PALLETE, false)
	&&  this->CScriptCompiler::StdDeclare("callmonster", "snsnn?", FUNC_CALLMONSTER, false)
	&&  this->CScriptCompiler::StdDeclare("addskill", "nnnn", FUNC_ADDSKILL, false)
	&&  this->CScriptCompiler::StdDeclare("cmdothernpc", "ss", FUNC_OTHERNPC_CMD, false)
	&&  this->CScriptCompiler::StdDeclare("strlocalvar", "ns", FUNC_STRLOCALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("InitTimer", ".", FUNC_INITTIMER, false)
	&&  this->CScriptCompiler::StdDeclare("setarenaeventsize", "n", FUNC_SETARENAEVENTSIZE, false)
	&&  this->CScriptCompiler::StdDeclare("makewaitingroom", "sn", FUNC_MAKEWAITINGROOM, false)
	&&  this->CScriptCompiler::StdDeclare("enablearena", ".", FUNC_ENABLEARENA, false)
	&&  this->CScriptCompiler::StdDeclare("disablearena", ".", FUNC_DISABLEARENA, false)
	&&  this->CScriptCompiler::StdDeclare("warpwaitingpctoarena", "snn", FUNC_WARPWAITINGPCTOARENA, false)
	&&  this->CScriptCompiler::StdDeclare("resetmymob", ".", FUNC_RESETMYMOB, false)
	&&  this->CScriptCompiler::StdDeclare("warpallpcinthemap", "snn", FUNC_WARPALLPCINTHEMAP, false)
	&&  this->CScriptCompiler::StdDeclare("broadcastinmap", "s", FUNC_BROADCASTINTHEMAP, false)
	&&  this->CScriptCompiler::StdDeclare("stoptimer", ".", FUNC_STOPTIMER, false)
	&&  this->CScriptCompiler::StdDeclare("addnpctimer", "sn", FUNC_ADDNPCTIMER, false)
	&&  this->CScriptCompiler::StdDeclare("subnpctimer", "sn", FUNC_SUBNPCTIMER, false)
	&&  this->CScriptCompiler::StdDeclare("enablenpc", "s", FUNC_ENABLENPC, false)
	&&  this->CScriptCompiler::StdDeclare("disablenpc", "s", FUNC_DISABLENPC, false)
	&&  this->CScriptCompiler::StdDeclare("callnpc", "snsnnn", FUNC_CALLNPC, false)
	&&  this->CScriptCompiler::StdDeclare("SetFeeZeny", "n", FUNC_SETFEEZENY, false)
	&&  this->CScriptCompiler::StdDeclare("SetFeeItem", "nn", FUNC_SETFEEITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SetReqLevel", "nn", FUNC_SETREQLEVEL, false)
	&&  this->CScriptCompiler::StdDeclare("SetTexJob", "n", FUNC_SETTEXJOB, false)
	&&  this->CScriptCompiler::StdDeclare("DisableItemMove", ".", FUNC_DISABLEITEMMOVE, false)
	&&  this->CScriptCompiler::StdDeclare("EnableItemMove", ".", FUNC_ENABLEITEMMOVE, false)
	&&  this->CScriptCompiler::StdDeclare("SuccessRefItem", "n", FUNC_SUCCESSREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("FailedRefItem", "n", FUNC_FAILEDREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SetEffectStatus", "n", FUNC_SETEFFECTSTATUS, false)
	&&  this->CScriptCompiler::StdDeclare("ResetStat", ".", FUNC_RESETSTAT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetSkill", ".", FUNC_RESETSKILL, false)
	&&  this->CScriptCompiler::StdDeclare("menu2", "s?", FUNC_MENU2, false)
	&&  this->CScriptCompiler::StdDeclare("ShowDigit", "n", FUNC_SHOWDIGIT, false)
	&&  this->CScriptCompiler::StdDeclare("EventAddSkill", "nn", FUNC_EVENT_ADD_SKILL, false)
	&&  this->CScriptCompiler::StdDeclare("EventDelSkill", "n", FUNC_EVENT_DEL_SKILL, false)
	&&  this->CScriptCompiler::StdDeclare("SetParameter", "nn", FUNC_SETPARAMETER, false)
	&&  this->CScriptCompiler::StdDeclare("Emotion", "sn", FUNC_EMOTION, false)
	&&  this->CScriptCompiler::StdDeclare("ChangeSpr", "sn", FUNC_CHANGESPR, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipCount", "n", FUNC_GETEQUIPCOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("AgitGet", "n", FUNC_AGITGET, false)
	&&  this->CScriptCompiler::StdDeclare("AgitGet2", "sn", FUNC_AGITGET2, false)
	&&  this->CScriptCompiler::StdDeclare("AgitSet", "nn", FUNC_AGITSET, false)
	&&  this->CScriptCompiler::StdDeclare("AgitFunc", "nnn", FUNC_AGITFUNC, false)
	&&  this->CScriptCompiler::StdDeclare("AgitNpcGet", "nn", FUNC_AGITNPCGET, false)
	&&  this->CScriptCompiler::StdDeclare("AgitNpcSet", "nnn", FUNC_AGITNPCSET, false)
	&&  this->CScriptCompiler::StdDeclare("IsGuildMaster", "n", FUNC_ISGUILDMASTER, false)
	&&  this->CScriptCompiler::StdDeclare("putmob2", "snnnnnnnnns", FUNC_PUTMOB2, false)
	&&  this->CScriptCompiler::StdDeclare("AgitRegister", "s", FUNC_AGITREGISTER, false)
	&&  this->CScriptCompiler::StdDeclare("broadcastinmap2", "snnnns", FUNC_BROADCASTINMAP2, false)
	&&  this->CScriptCompiler::StdDeclare("broadcastserver", "snnnns", FUNC_BROADCASTSERVER, false)
	&&  this->CScriptCompiler::StdDeclare("sound", "snnn", FUNC_SOUND, false)
	&&  this->CScriptCompiler::StdDeclare("dlgwritestr", ".", FUNC_DLGWRITESTR, false)
	&&  this->CScriptCompiler::StdDeclare("GetDamagedItemNum", ".", FUNC_GETDAMAGEDITEMNUM, false)
	&&  this->CScriptCompiler::StdDeclare("RepairDamagedItem", ".", FUNC_REPAIRDAMAGEDITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SavePPL", "n", FUNC_SAVEPPL, false)
	&&  this->CScriptCompiler::StdDeclare("AgitEmblemFlag", "s", FUNC_AGITEMBLEMFLAG, false)
	&&  this->CScriptCompiler::StdDeclare("hpdrain", "n", FUNC_HPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("spdrain", "n", FUNC_SPDRAIN, false)
	&&  this->CScriptCompiler::StdDeclare("getexp", "n", FUNC_GETEXP, false)
	&&  this->CScriptCompiler::StdDeclare("dropexp", "n", FUNC_DROPEXP, false)
	&&  this->CScriptCompiler::StdDeclare("ServerTime", ".", FUNC_SERVERTIME, false)
	&&  this->CScriptCompiler::StdDeclare("GetLocalVarName", "n", FUNC_GETLOCALVARNAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetMarried", ".", FUNC_GETMARRIED, false)
	&&  this->CScriptCompiler::StdDeclare("countdown", "n", FUNC_COUNTDOWN, false)
	&&  this->CScriptCompiler::StdDeclare("GuildName", ".", FUNC_GETGUILDNAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetNeighborPcNumber", "n", FUNC_GETNEIGHBORPCNUMBER, false)
	&&  this->CScriptCompiler::StdDeclare("getnameditem", "nn", FUNC_GETNAMEDITEM, false)
	&&  this->CScriptCompiler::StdDeclare("dropnameditem", "nn", FUNC_DROPNAMEDITEM, false)
	&&  this->CScriptCompiler::StdDeclare("GetCountOfMyNameItem", "n", FUNC_GETCOUNTFOMYNAMEITEM, false)
	&&  this->CScriptCompiler::StdDeclare("ChangeHairStyle", "n", FUNC_CHANGE_HAIRSTYLE, false)
	&&  this->CScriptCompiler::StdDeclare("ShowEffect", "sn", FUNC_SHOWEFFECT, false)
	&&  this->CScriptCompiler::StdDeclare("falcon", "n", FUNC_FALCON, false)
	&&  this->CScriptCompiler::StdDeclare("peco", "n", FUNC_PECO, false)
	&&  this->CScriptCompiler::StdDeclare("CheckMaxWeight", "nn", FUNC_CHECK_MAXWEIGHT, false)
	&&  this->CScriptCompiler::StdDeclare("CheckMaxCount", "nn", FUNC_CHECK_MAXCOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("CheckMaxZeny", "n", FUNC_CHECK_MAXZENY, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventZenyName", "n", FUNC_MGETEVENT_ZENYNAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItemName", "n", FUNC_MGETEVENT_ITEMNAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventZeny", "n", FUNC_MGETEVENT_ZENY, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItem", "n", FUNC_MGETEVENT_ITEM, false)
	&&  this->CScriptCompiler::StdDeclare("CreateGuild", "s", FUNC_CREATE_GUILD, false)
	&&  this->CScriptCompiler::StdDeclare("CreateGlobalVar", "sn", FUNC_CREATEGLOBALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("GetGlobalVar", "s", FUNC_GETGLOBALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("SetGlobalVar", "sn", FUNC_SETGLOBALVAR, false)
	&&  this->CScriptCompiler::StdDeclare("StrCmp", "ss", FUNC_STRCMP, false)
	&&  this->CScriptCompiler::StdDeclare("StrStr", "ss", FUNC_STRSTR, false)
	&&  this->CScriptCompiler::StdDeclare("UpgradeGuildLevel", ".", FUNC_UPGRADEGUILDLEVEL, false)
	&&  this->CScriptCompiler::StdDeclare("CreateGlobalStr", "ss", FUNC_CREATEGLOBALSTR, false)
	&&  this->CScriptCompiler::StdDeclare("GetGlobalStr", "s", FUNC_GETGLOBALSTR, false)
	&&  this->CScriptCompiler::StdDeclare("SetGlobalStr", "ss", FUNC_SETGLOBALSTR, false)
	&&  this->CScriptCompiler::StdDeclare("divorce", ".", FUNC_DIVORCE, false)
	&&  this->CScriptCompiler::StdDeclare("GetTablePoint", ".", FUNC_GET_TABLEPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("AddTablePoint", "n", FUNC_ADD_TABLEPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("DelTablePoint", "n", FUNC_DEL_TABLEPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("DataMoveToPVP", ".", FUNC_PCDATA_MOVE_TO_PVP, false)
	&&  this->CScriptCompiler::StdDeclare("GetPVPPoint", ".", FUNC_GETPVPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("SetPVPPoint", "n", FUNC_SETPVPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItemID", "n", FUNC_MGETEVENT_ITEMID, false)
	&&  this->CScriptCompiler::StdDeclare("getJexp", "n", FUNC_GETJOBEXP, false)
	&&  this->CScriptCompiler::StdDeclare("dropJexp", "n", FUNC_DROPJOBEXP, false)
	&&  this->CScriptCompiler::StdDeclare("ChkSkill", "n", FUNC_CHKSKILL, false)
	&&  this->CScriptCompiler::StdDeclare("GetBODYSTATE", "nn", FUNC_GETBODYSTATE, false)
	&&  this->CScriptCompiler::StdDeclare("GetHEALTHSTATE", "nn", FUNC_GETHEALTHSTATE, false)
	&&  this->CScriptCompiler::StdDeclare("UseSkillToPC", "nnnn", FUNC_USESKILL_TO_PC, false)
	&&  this->CScriptCompiler::StdDeclare("IsBaby", ".", FUNC_ISBABY, false)
	&&  this->CScriptCompiler::StdDeclare("GetLotto", "n", FUNC_GETLOTTO, false)
	&&  this->CScriptCompiler::StdDeclare("SetLotto", "nnnnnn", FUNC_SETLOTTO, false)
	&&  this->CScriptCompiler::StdDeclare("InitLotto", ".", FUNC_INITLOTTO, false)
	&&  this->CScriptCompiler::StdDeclare("OpenAuction", ".", FUNC_OPENAUCTION, false)
	&&  this->CScriptCompiler::StdDeclare("OpenMailing", ".", FUNC_OPENMAILING, false)
	&&  this->CScriptCompiler::StdDeclare("StripPC", "n", FUNC_STRIPTPC, false)
	&&  this->CScriptCompiler::StdDeclare("PushPC", "nn", FUNC_PUSHPC, false)
	&&  this->CScriptCompiler::StdDeclare("ItemDown", "nnnn", FUNC_ITEMDOWN, false)
	&&  this->CScriptCompiler::StdDeclare("SetNumArray", "nn", FUNC_SETNUMARRAY, false)
	&&  this->CScriptCompiler::StdDeclare("GetNumArray", "n", FUNC_GETNUMARRAY, false)
	&&  this->CScriptCompiler::StdDeclare("ShuffleNumbers", "nn", FUNC_SHUFFLENUMBERS, false)
	&&  this->CScriptCompiler::StdDeclare("PartyName", ".", FUNC_PARTYNAME, false)
	&&  this->CScriptCompiler::StdDeclare("ChangeSpeed", "nn", FUNC_CHANGESPEED, false)
	&&  this->CScriptCompiler::StdDeclare("IsSiegeTime", ".", FUNC_ISSIEGETIME, false)
	&&  this->CScriptCompiler::StdDeclare("ConsumeSpecialItem", "n", FUNC_CONSUMESPECIALITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SetItemPartyInMap", "nn", FUNC_SETITEMPARTYINMAP, false)
	&&  this->CScriptCompiler::StdDeclare("IsHuntingListFull", ".", FUNC_ISHUNTINGLISTFULL, false)
	&&  this->CScriptCompiler::StdDeclare("FindHuntingList", "n", FUNC_FINDHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("AddHuntingList", "n", FUNC_ADDHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("DeleteHuntingList", "n", FUNC_DELETEHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("DisplayHuntingList", ".", FUNC_DISPLAYHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("DisplayHuntingList2", ".", FUNC_DISPLAYHUNTINGLIST2, false)
	&&  this->CScriptCompiler::StdDeclare("SetHuntingList", "nn", FUNC_SETHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("ClearHuntingList", ".", FUNC_CLEARHUNTINGLIST, false)
	&&  this->CScriptCompiler::StdDeclare("IsTimeListFull", ".", FUNC_ISTIMELISTFULL, false)
	&&  this->CScriptCompiler::StdDeclare("FindTimeList", "n", FUNC_FINDTIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("AddTimeList", "n", FUNC_ADDTIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("DeleteTimeList", "n", FUNC_DELETETIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("DisplayTimeList", ".", FUNC_DISPLAYTIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("SetTimeList", "nn", FUNC_SETTIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("ClearTimeList", ".", FUNC_CLEARTIMELIST, false)
	&&  this->CScriptCompiler::StdDeclare("ChangeCellType", "nnn", FUNC_CHANGECELLTYPE, false)
	&&  this->CScriptCompiler::StdDeclare("GetCellType", "nn", FUNC_GETCELLTYPE, false)
	&&  this->CScriptCompiler::StdDeclare("IsPcCafe", ".", FUNC_ISPCCAFE, false)
	&&  this->CScriptCompiler::StdDeclare("GetPayType", ".", FUNC_GETPAYTYPE, false)
	&&  this->CScriptCompiler::StdDeclare("GetConnectionArea", ".", FUNC_GETCONNECTIONAREA, false)
	&&  this->CScriptCompiler::StdDeclare("GetConnectionState", ".", FUNC_GETCONNECTIONSTATE, false)
	&&  this->CScriptCompiler::StdDeclare("GetPetEgg", "n", FUNC_GETPETEGG, false)
	&&  this->CScriptCompiler::StdDeclare("CashTrader", "ssnnnn", FUNC_CASHTRADER, true)
	&&  this->CScriptCompiler::StdDeclare("CashShop", "s", FUNC_CASHSHOP, false)
	&&  this->CScriptCompiler::StdDeclare("AddexpTime", "nn", FUNC_ADDEXPTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SubexpTime", "n", FUNC_SUBEXPTIME, false)
	&&  this->CScriptCompiler::StdDeclare("AddReceiveItem", "nn", FUNC_ADDRECEIVEITEM, false)
	&&  this->CScriptCompiler::StdDeclare("GetAdvEquipIsSuccessRefinery", "n", FUNC_ADVEQUIP_ISSUCCESSREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("Partycall", ".", FUNC_PARTYCALL, false)
	&&  this->CScriptCompiler::StdDeclare("putboss", "snnnnnnnnn", FUNC_PUTBOSS, false)
	&&  this->CScriptCompiler::StdDeclare("UseBossPerception", "n", FUNC_USEBOSSPERCEPTION, false)
	&&  this->CScriptCompiler::StdDeclare("SkillToMe", "nn", FUNC_SKILLTOME, false)
	&&  this->CScriptCompiler::StdDeclare("UseHuntingList", ".", FUNC_UseHuntingList, false)
	&&  this->CScriptCompiler::StdDeclare("CheckHuntingList", "n", FUNC_CheckHuntingList, false)
	&&  this->CScriptCompiler::StdDeclare("item2", "n", FUNC_ITEM2, true)
	&&  this->CScriptCompiler::StdDeclare("WeaponProperty", "nn", FUNC_WEAPONPROPERTY, false)
	&&  this->CScriptCompiler::StdDeclare("ReadBook", "nn", FUNC_READBOOK, false)
	&&  this->CScriptCompiler::StdDeclare("Mercenary_Summon", "n", FUNC_MERCENARY_SUMMON, false)
	&&  this->CScriptCompiler::StdDeclare("Mercenary_HealHP", "n", FUNC_MERCENARY_HEALHP, false)
	&&  this->CScriptCompiler::StdDeclare("Mercenary_HealSP", "n", FUNC_MERCENARY_HEALSP, false)
	&&  this->CScriptCompiler::StdDeclare("GetMercenaryTotalSummonNum", "n", FUNC_GETMERCENARYTOTALSUMMONNUM, false)
	&&  this->CScriptCompiler::StdDeclare("GetMercenaryFaith", "n", FUNC_GETMERCENARYFAITH, false)
	&&  this->CScriptCompiler::StdDeclare("SubMercenaryFaith", "nn", FUNC_SUBMERCENARYFAITH, false)
	&&  this->CScriptCompiler::StdDeclare("AddMercenaryFaith", "nn", FUNC_ADDMERCENARYFAITH, false)
	&&  this->CScriptCompiler::StdDeclare("npc2", "ssnnnnnnn", FUNC_NPC2, true)
	&&  this->CScriptCompiler::StdDeclare("OnMoveNpcCmd:", ".", FUNC_ONMOVENPCCMD, true)
	&&  this->CScriptCompiler::StdDeclare("MovePos", "nn", FUNC_MOVEPOS, false)
	&&  this->CScriptCompiler::StdDeclare("MoveWait", "n", FUNC_MOVEWAIT, false)
	&&  this->CScriptCompiler::StdDeclare("Refinery", "n", FUNC_REFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("Mercenary_Condition", "nnn", FUNC_MERCENARY_CONDITION, false)
	&&  this->CScriptCompiler::StdDeclare("AddNeverknockback", "n", FUNC_ADDNEVERKNOCKBACK, false)
	&&  this->CScriptCompiler::StdDeclare("GetAdvEquipPercentRefinery", "n", FUNC_GETADVEQUIPPERCENTREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("ReLoadMobileEvent", ".", FUNC_RELOAD_MOBILE_EVENT, false)
	&&  this->CScriptCompiler::StdDeclare("SetTempTime", "n", FUNC_SETTEMPTIME, false)
	&&  this->CScriptCompiler::StdDeclare("ElapseTempTime", "n", FUNC_ELAPSETEMPTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SubNeverknockback", "n", FUNC_SUBNEVERKNOCKBACK, false)
	&&  this->CScriptCompiler::StdDeclare("GetWeaponClass", "n", FUNC_GETWEAPONCLASS, false)
	&&  this->CScriptCompiler::StdDeclare("GetEquipSlotAmount", "n", FUNC_GETEQUIPSLOTAMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("AddHealValue", "n", FUNC_ADDHEALVALUE, false)
	&&  this->CScriptCompiler::StdDeclare("SubHealValue", "n", FUNC_SUBHEALVALUE, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpell_MAGATKED", "nnnn", FUNC_SETAUTOSPELL_MAGATKED, false)
	&&  this->CScriptCompiler::StdDeclare("AddHPAmount_MAGKill", "n", FUNC_ADDHPAMOUNT_MAGKILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubHPAmount_MAGKill", "n", FUNC_SUBHPAMOUNT_MAGKILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddSPAmount_MAGKill", "n", FUNC_ADDSPAMOUNT_MAGKILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubSPAmount_MAGKill", "n", FUNC_SUBSPAMOUNT_MAGKILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddSpellDelay", "n", FUNC_ADDSPELLDELAY, false)
	&&  this->CScriptCompiler::StdDeclare("SubSpellDelay", "n", FUNC_SUBSPELLDELAY, false)
	&&  this->CScriptCompiler::StdDeclare("AddSpecificSpellCastTime", "nn", FUNC_ADDSPECIFICSPELLCASTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SubSpecificSpellCastTime", "nn", FUNC_SUBSPECIFICSPELLCASTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("AddMdamage_Race", "nn", FUNC_ADDMDAMAGE_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("SubMdamage_Race", "nn", FUNC_SUBMDAMAGE_RACE, false)
	&&  this->CScriptCompiler::StdDeclare("AddMdamage_Class", "nn", FUNC_ADDMDAMAGE_CLASS, false)
	&&  this->CScriptCompiler::StdDeclare("SubMdamage_Class", "nn", FUNC_SUBMDAMAGE_CLASS, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreMdefRace", "nn", FUNC_SETIGNOREMDEFRACE, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreMdefRace", "nn", FUNC_RESETIGNOREMDEFRACE, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreMdefClass", "nn", FUNC_SETIGNOREMDEFCLASS, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreMdefClass", "nn", FUNC_RESETIGNOREMDEFCLASS, false)
	&&  this->CScriptCompiler::StdDeclare("SetHPAmountTime", "nnn", FUNC_SETHPAMOUNTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("ResetHPAmountTime", "nnn", FUNC_RESETHPAMOUNTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SetSPAmountTime", "nnn", FUNC_SETSPAMOUNTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("ResetSPAmountTime", "nnn", FUNC_RESETSPAMOUNTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreDefRace_Percent", "nn", FUNC_SETIGNOREDEFRACE_PERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreDefRace_Percent", "nn", FUNC_RESETIGNOREDEFRACE_PERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("SetIgnoreDefClass_Percent", "nn", FUNC_SETIGNOREDEFCLASS_PERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetIgnoreDefClass_Percent", "nn", FUNC_RESETIGNOREDEFCLASS_PERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("GetInventoryRemainCount", "nn", FUNC_GETINVENTORYREMAINCOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoWeapon", "nnn", FUNC_SETAUTOWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("ResetAutoWeapon", "nnn", FUNC_RESETAUTOWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoMweapon", "nnn", FUNC_SETAUTOMWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("ResetAutoMweapon", "nnn", FUNC_RESETAUTOMWEAPON, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoAttacked", "nnn", FUNC_SETAUTOATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("ResetAutoAttacked", "nnn", FUNC_RESETAUTOATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoMAttacked", "nnn", FUNC_SETAUTOMATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("ResetAutoMAttacked", "nnn", FUNC_RESETAUTOMATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("ResetReceiveItem_Group", "n", FUNC_RESETRECEIVEITEM_GROUP, false)
	&&  this->CScriptCompiler::StdDeclare("Buff", "s", FUNC_BUFF, true)
	&&  this->CScriptCompiler::StdDeclare("SetBuff", "snn", FUNC_SETBUFF, false)
	&&  this->CScriptCompiler::StdDeclare("GetBuffValue", "s", FUNC_GETBUFFVALUE, false)
	&&  this->CScriptCompiler::StdDeclare("AddHealModifyPercent", "n", FUNC_ADDHEALMODIFYPERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("SubHealModifyPercent", "n", FUNC_SUBHEALMODIFYPERCENT, false)
	&&  this->CScriptCompiler::StdDeclare("SetHPPercentTime", "nnn", FUNC_SETHPPERCENTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("ResetHPPercentTime", "nnn", FUNC_RESETHPPERCENTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("SetSPPercentTime", "nnn", FUNC_SETSPPERCENTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("ResetSPPercentTime", "nnn", FUNC_RESETSPPERCENTTIME, false)
	&&  this->CScriptCompiler::StdDeclare("LoudSpeaker", "snnnns", FUNC_LOUDSPEAKER, false)
	&&  this->CScriptCompiler::StdDeclare("SetTargetAttacked_Buff", "nnsnn", FUNC_SETTARGETATTACKED_BUFF, false)
	&&  this->CScriptCompiler::StdDeclare("ResetTargetAttacked_Buff", "nnsnn", FUNC_RESETTARGETATTACKED_BUFF, false)
	&&  this->CScriptCompiler::StdDeclare("GetMapName", ".", FUNC_GETMAPNAME, false)
	&&  this->CScriptCompiler::StdDeclare("setquest", "n", FUNC_SETQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("changequest", "nn", FUNC_CHANGQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("erasequest", "n", FUNC_ERASEQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("completequest", "n", FUNC_COMPLATEQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("completequest_between", "nn", FUNC_COMPLETEQUEST_BETWEEN, false)
	&&  this->CScriptCompiler::StdDeclare("recall_completequest", "n", FUNC_RECALL_COMPLETEQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("isbegin_quest", "n", FUNC_ISBEGINQUEST, false)
	&&  this->CScriptCompiler::StdDeclare("checkquest_hunting", "n", FUNC_CHECKQUEST_HUNTING, false)
	&&  this->CScriptCompiler::StdDeclare("checkquest_playtime", "n", FUNC_CHECKQUEST_PLAYTIME, false)
	&&  this->CScriptCompiler::StdDeclare("GetLastSiegeMsg", "s", FUNC_GETLASTSIEGEMSG, false)
	&&  this->CScriptCompiler::StdDeclare("DataMoveTo_Sakray", ".", FUNC_PCDATA_MOVE_TO_SAKRAY, false)
	&&  this->CScriptCompiler::StdDeclare("callguardian", "snsnn", FUNC_CALLGUARDIAN, false)
	&&  this->CScriptCompiler::StdDeclare("IsPremiumPcCafe", ".", FUNC_ISPREMIUMPCCAFE, false)
	&&  this->CScriptCompiler::StdDeclare("MD_Subscription", "s", FUNC_MDUNGEON_SUBSCRIPTION, false)
	&&  this->CScriptCompiler::StdDeclare("MD_Enter", "s", FUNC_MDUNGEON_ENTER, false)
	&&  this->CScriptCompiler::StdDeclare("CampCode", "snn", FUNC_CAMPCODE, false)
	&&  this->CScriptCompiler::StdDeclare("GetCampCode", ".", FUNC_GETCAMPCODE, false)
	&&  this->CScriptCompiler::StdDeclare("CallCampMob", "nnnss", FUNC_CALLCAMPMOB, false)
	&&  this->CScriptCompiler::StdDeclare("SetRP2", "nn", FUNC_SETRP2, false)
	&&  this->CScriptCompiler::StdDeclare("MassSetRP2", "snn", FUNC_MASSSETRP2, false)
	&&  this->CScriptCompiler::StdDeclare("PlayerToRP", "n", FUNC_PLAYERTORP, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventZenyName_Exculusive", "n", FUNC_MGETEVENT_ZENYNAME_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItemName_Exculusive", "n", FUNC_MGETEVENT_ITEMNAME_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventZeny_Exculusive", "n", FUNC_MGETEVENT_ZENY_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItem_Exculusive", "n", FUNC_MGETEVENT_ITEM_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("GetMEventItemID_Exculusive", "n", FUNC_MGETEVENT_ITEMID_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("ReLoadMobileEvent_Exculusive", ".", FUNC_MGETEVENT_RELOAD_EXCULUSEIVE, false)
	&&  this->CScriptCompiler::StdDeclare("MD_List", "sss", FUNC_MDUNGEON_LIST, false)
	&&  this->CScriptCompiler::StdDeclare("MD_Destroy", "s", FUNC_MDUNGEON_DESTROY, false)
	&&  this->CScriptCompiler::StdDeclare("PlusCampPoint", "sn", FUNC_PLUSCAMPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("MinusCampPoint", "sn", FUNC_MINUSCAMPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("GetCampPoint", "s", FUNC_GETCAMPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("ResetCampPoint", ".", FUNC_RESETCAMPPOINT, false)
	&&  this->CScriptCompiler::StdDeclare("CheckSiegeTime", "n", FUNC_CHECKSIEGETIME, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_MATK", "nnn", FUNC_ADDSTATE_MATK, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_MATK", "nnn", FUNC_SUBSTATE_MATK, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_MAttacked", "nnn", FUNC_ADDSTATE_MATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_MAttacked", "nnn", FUNC_SUBSTATE_MATTACKED, false)
	&&  this->CScriptCompiler::StdDeclare("GetMDMapName", "s", FUNC_MDUNGEON_MAPNAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetMDNpcName", "s", FUNC_MDUNGEON_NPCNAME, false)
	&&  this->CScriptCompiler::StdDeclare("MD_Npc", "ssnnnnnn", FUNC_MDUNGEON_NPC, true)
	&&  this->CScriptCompiler::StdDeclare("MD_Warp", "ssnnnn", FUNC_MDUNGEON_WAP, true)
	&&  this->CScriptCompiler::StdDeclare("MD_Hiddenwarp", "ssnnnn", FUNC_MDUNGEON_HIDDENWAP, true)
	&&  this->CScriptCompiler::StdDeclare("MD_Putmob", "snnnnnnnnn", FUNC_MDUNGEON_PUTMOB, false)
	&&  this->CScriptCompiler::StdDeclare("Mymobskilluse", "snnnn", FUNC_MYMOBSKILLUSE, false)
	&&  this->CScriptCompiler::StdDeclare("WhereMymobX", "s", FUNC_WHEREMYMOB_X, false)
	&&  this->CScriptCompiler::StdDeclare("WhereMymobY", "s", FUNC_WHEREMYMOB_Y, false)
	&&  this->CScriptCompiler::StdDeclare("WideMobskilluse", "nnnnnnn", FUNC_WIDEMOBSKILLUSE, false)
	&&  this->CScriptCompiler::StdDeclare("WideMobskilluse2", "nnnsnnnn", FUNC_WIDEMOBSKILLUSE2, false)
	&&  this->CScriptCompiler::StdDeclare("MD_OpenState", "n", FUNC_MDUNGEON_OPENSTATE, false)
	&&  this->CScriptCompiler::StdDeclare("AddHPDrain_100", "n", FUNC_ADDHPDRAIN_100, false)
	&&  this->CScriptCompiler::StdDeclare("SubHPDrain_100", "n", FUNC_SUBHPDRAIN_100, false)
	&&  this->CScriptCompiler::StdDeclare("CreatePackage", ".", FUNC_CREATEPACKAGE, false)
	&&  this->CScriptCompiler::StdDeclare("IsBender", ".", FUNC_ISBENDER, false)
	&&  this->CScriptCompiler::StdDeclare("MoveResume", ".", FUNC_MOVERESUME, false)
	&&  this->CScriptCompiler::StdDeclare("MoveReturn", ".", FUNC_MOVERETURN, false)
	&&  this->CScriptCompiler::StdDeclare("MoveSpeed", "n", FUNC_MOVESPEED, false)
	&&  this->CScriptCompiler::StdDeclare("GetNpcPosition", "s", FUNC_GETNPCPOSITION, false)
	&&  this->CScriptCompiler::StdDeclare("AddReceiveItem_Equip", "n", FUNC_ADDRECEIVEITEM_EQUIP, false)
	&&  this->CScriptCompiler::StdDeclare("SubReceiveItem_Equip", "n", FUNC_SUBRECEIVEITEM_EQUIP, false)
	&&  this->CScriptCompiler::StdDeclare("AddOnlyJobExpTime", "nn", FUNC_ADDONLYJOBEXPTIME, false)
	&&  this->CScriptCompiler::StdDeclare("progress_bar", "sn", FUNC_PROGRESS_BAR, false)
	&&  this->CScriptCompiler::StdDeclare("MercenaryCheck", ".", FUNC_MERCENARYCHECK, false)
	&&  this->CScriptCompiler::StdDeclare("MercenaryType", ".", FUNC_MERCENARYTYPE, false)
	&&  this->CScriptCompiler::StdDeclare("IsFreeServer", ".", FUNC_ISFREESERVER, false)
	&&  this->CScriptCompiler::StdDeclare("SetSkillAutoSpell", "nnnnn", FUNC_SETSKILLAUTOSPELL, false)
	&&  this->CScriptCompiler::StdDeclare("ResetSkillAutoSpell", "nnnnn", FUNC_RESETSKILLAUTOSPELL, false)
	&&  this->CScriptCompiler::StdDeclare("SetSkillActivate", "nnnn", FUNC_SETSKILLACTIVATE, false)
	&&  this->CScriptCompiler::StdDeclare("ResetSkillActivate", "nnnn", FUNC_RESETSKILLACTIVATE, false)
	&&  this->CScriptCompiler::StdDeclare("GetActivated_Skill", ".", FUNC_GETACTIVATED_SKILL, false)
	&&  this->CScriptCompiler::StdDeclare("GetDeactivated_Skill", ".", FUNC_GETDEACTIVATED_SKILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddState_SKID", "nnnn", FUNC_ADDSTATE_SKID, false)
	&&  this->CScriptCompiler::StdDeclare("SubState_SKID", "nnnn", FUNC_SUBSTATE_SKID, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpellMagic", "nnnn", FUNC_SETAUTOSPELLMAGIC, false)
	&&  this->CScriptCompiler::StdDeclare("ResetAutoSpellMagic", "nnnn", FUNC_RESETAUTOSPELLMAGIC, false)
	&&  this->CScriptCompiler::StdDeclare("run_npc", "ssnnnnnn", FUNC_RUN_NPC, false)
	&&  this->CScriptCompiler::StdDeclare("run_npctrader", "ssnnnnnn", FUNC_RUN_NPCTRADER, false)
	&&  this->CScriptCompiler::StdDeclare("OnCampCommand:", ".", FUNC_ONCAMPCOMMAND, true)
	&&  this->CScriptCompiler::StdDeclare("check_partyjob", ".", FUNC_CHECKPARTYJOB, false)
	&&  this->CScriptCompiler::StdDeclare("clearbuff", ".", FUNC_CLEARBUFF, false)
	&&  this->CScriptCompiler::StdDeclare("check_alive", "s", FUNC_CHECKALIVE, false)
	&&  this->CScriptCompiler::StdDeclare("kvm_npc", "ssnnnnnn", FUNC_KVM_NPC, true)
	&&  this->CScriptCompiler::StdDeclare("kvm_start_alivecheck", ".", FUNC_KVM_START_ALIVECHECK, false)
	&&  this->CScriptCompiler::StdDeclare("pvprankcheck", ".", FUNC_PVPRANKCHECK, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpell_MLEATK", "nnnn", FUNC_SETAUTOSPELL_MLEATK, false)
	&&  this->CScriptCompiler::StdDeclare("SetAutoSpell_RANGEATK", "nnnn", FUNC_SETAUTOSPELL_RANGEATK, false)
	&&  this->CScriptCompiler::StdDeclare("kvm_npc_noti", "s", FUNC_KVM_NPC_NOTI, false)
	&&  this->CScriptCompiler::StdDeclare("getarenaeventsize", ".", FUNC_GETARENAEVENTSIZE, false)
	&&  this->CScriptCompiler::StdDeclare("SetMakableRuneItemList", "n", FUNC_SETMAKABLERUNEITEMLIST, false)
	&&  this->CScriptCompiler::StdDeclare("IsSuccessRuneUse", "n", FUNC_ISSUCCESSRUNEUSE, false)
	&&  this->CScriptCompiler::StdDeclare("SetMakableNewPoisonList", ".", FUNC_SETMAKABLENEWPOISONLIST, false)
	&&  this->CScriptCompiler::StdDeclare("GetItemSocket", "nnnnn", FUNC_GETITEMSOCKET, false)
	&&  this->CScriptCompiler::StdDeclare("GetPetRelationship", ".", FUNC_GETPETRELATIONSHIP, false)
	&&  this->CScriptCompiler::StdDeclare("AddMDamage_Name", "nsn", FUNC_ADDMDAMAGE_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("SubMDamage_Name", "nsn", FUNC_SUBMDAMAGE_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("GetNonSlotItemSock", "nnnnn", FUNC_GETNONSLOTITEMSOCK, false)
	&&  this->CScriptCompiler::StdDeclare("IsEffectStatus", "n", FUNC_ISEFFECTSTATUS, false)
	&&  this->CScriptCompiler::StdDeclare("GetMyMercenary", ".", FUCN_GETMYMERCENARY, false)
	&&  this->CScriptCompiler::StdDeclare("ErrorLog", "s", FUNC_ERRORLOG, false)
	&&  this->CScriptCompiler::StdDeclare("AddReceiveItem_Name", "ssn", FUNC_ADDRECEIVEITEM_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("SubReceiveItem_Name", "ssn", FUNC_SUBRECEIVEITEM_NAME, false)
	&&  this->CScriptCompiler::StdDeclare("IsMadogear", ".", FUNC_ISMADOGEAR, false)
	&&  this->CScriptCompiler::StdDeclare("SetMadogear", "s", FUNC_SETMADOGEAR, false)
	&&  this->CScriptCompiler::StdDeclare("AddSFCTConsumeAmount", "nnn", FUNC_ADD_SFCT_CONSUME_AMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("SubSFCTConsumeAmount", "nnn", FUNC_SUB_SFCT_CONSUME_AMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("AddSFCTConsumePermill", "nnn", FUNC_ADD_SFCT_CONSUME_PERMILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubSFCTConsumePermill", "nnn", FUNC_SUB_SFCT_CONSUME_PERMILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddSFCTEquipAmount", "nnn", FUNC_ADD_SFCT_EQUIP_AMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("SubSFCTEquipAmount", "nnn", FUNC_SUB_SFCT_EQUIP_AMOUNT, false)
	&&  this->CScriptCompiler::StdDeclare("AddSFCTEquipPermill", "nnn", FUNC_ADD_SFCT_EQUIP_PERMILL, false)
	&&  this->CScriptCompiler::StdDeclare("SubSFCTEquipPermill", "nnn", FUNC_SUB_SFCT_EQUIP_PERMILL, false)
	&&  this->CScriptCompiler::StdDeclare("AddAttrTolerace_Disregard", "n?", FUNC_ADDATTRTOLERACE_DISREGARD, false)
	&&  this->CScriptCompiler::StdDeclare("SubAttrTolerace_Disregard", "n?", FUNC_SUBATTRTOLERACE_DISREGARD, false)
	&&  this->CScriptCompiler::StdDeclare("GetExdEquipIsSuccessRefinery", "n", FUNC_GETEXDEQUIPISSUCCESSREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("GetExdAdvEquipIsSuccessRefinery", "n", FUNC_GETEXDADVEQUIPISSUCCESSREFINERY, false)
	&&  this->CScriptCompiler::StdDeclare("DownRefItem", "n", FUNC_DOWNREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("DownAdvRefItem", "n", FUNC_DOWNADVREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SuccessRandomRefItem", "nnn", FUNC_SUCCESSRANDREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("SuccessRandomAdvRefItem", "nnn", FUNC_SUCCESSRANDADVREFITEM, false)
	&&  this->CScriptCompiler::StdDeclare("BattlePlayModeNoti", "n", FUNC_BATTLEPLAYMODENOTI, false)
	&&  this->CScriptCompiler::StdDeclare("OnCampCommand2:", "s", FUNC_ONCAMPCOMMAND2, true)
	&&  this->CScriptCompiler::StdDeclare("InterOther", "nnnn", FUNC_INTEROTHER, true)
	&&  this->CScriptCompiler::StdDefine("MALE", SEX_MALE)
	&&  this->CScriptCompiler::StdDefine("FEMALE", SEX_FEMALE)
	&&  this->CScriptCompiler::StdDefine("DEFAULT_WIDTH", 10)
	&&  this->CScriptCompiler::StdDefine("DEFAULT_HEIGHT", 10)
	&&  this->CScriptCompiler::StdDefine("DEFAULT_DIRECTION", 0)
	&&  this->CScriptCompiler::StdDefine("DEFAULT_SPEED", 300)
	&&  this->CScriptCompiler::StdDefine("on", 1)
	&&  this->CScriptCompiler::StdDefine("off", 0)
	&&  this->CScriptCompiler::StdDefine("FW_DONTCARE", 0)
	&&  this->CScriptCompiler::StdDefine("FW_THIN", 100)
	&&  this->CScriptCompiler::StdDefine("FW_EXTRALIGHT", 200)
	&&  this->CScriptCompiler::StdDefine("FW_LIGHT", 300)
	&&  this->CScriptCompiler::StdDefine("FW_NORMAL", 400)
	&&  this->CScriptCompiler::StdDefine("FW_MEDIUM", 500)
	&&  this->CScriptCompiler::StdDefine("FW_SEMIBOLD", 600)
	&&  this->CScriptCompiler::StdDefine("FW_BOLD", 700)
	&&  this->CScriptCompiler::StdDefine("FW_EXTRABOLD", 800)
	&&  this->CScriptCompiler::StdDefine("FW_HEAVY", 900)
	&&  this->CScriptCompiler::StdDefine("CELLINFO_DEFAULT", 0)
	&&  this->CScriptCompiler::StdDefine("CELLINFO_RED", 1)
	&&  this->CScriptCompiler::StdDefine("CELLINFO_BLUE", 5)
	);
}
